import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "next-frontend-starter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster position="bottom-right" toastOptions={{ duration: 5000 }} />
        <nav className="spac-x-6 flex w-full bg-gray-500 p-4">
          <h1 className="font-bold">ÁLK Utazási Iroda</h1>
          <Link className="cursor-pointertransition-transform hover:scale-90 ml-5" href="/journeys">
            Kínálat
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
